### ISSUE TITLE
Hỏi: cách thêm cách thành phố khác.

### ISSUE THREAD

**Issue by vuthao** [phamdinhhau/nukeviet-weather#2]
Xin hỏi tác giả, nếu tôi muốn thêm các thành số khác thì mã lấy ở đâu.

Nếu chỉ và có danh sách tôi sẽ lập trình thêm chức anwng này, chứ làm sao nhớ mã nó được nhỉ.

**Comment by phamdinhhau** [comment]
@vuthao  có thể vào đây tìm các thành phố https://weather.yahoo.com/. Chi tiết mình đã viết trong bài: http://forum.nukeviet.vn/viewtopic.php?f=166&t=32084.
