### ISSUE TITLE
Mã nguồn file weather.min.js

### ISSUE THREAD

**Issue by vuthao** [phamdinhhau/nukeviet-weather#3]
Hiện tại trong project có file weather.min.js đã bị nén lại, nếu muốn chỉnh sửa sẽ khó khăn.

Tác giả có thể cung cấp file chưa nén để chúng ta tiện phát triển.

**Comment by phamdinhhau** [comment]
File js chưa nén đây nha @vuthao 
https://drive.google.com/file/d/0B-KcGnT3eY9nem0zRVZMXzNpZFk/view?usp=sharing
